# Generated by Django 6.0.2 on 2026-03-02 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={},
        ),
    ]
