# Generated by Django 6.0.2 on 2026-03-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_members_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='member_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='members',
            table=None,
        ),
    ]
